services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - backend
      - frontend
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure
  db:
    image: postgres:9.4
    networks:
      - backend
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - db-data:/vat/lib/postgresql/data
    deploy:
      replicas: 1
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - "6969:80"
    networks:
      - backend
    deploy:
      replicas: 1

volumes:
  db-data:
    external: true

networks:
  backend:
    external: true
  frontend: 
    external: true

# docker stack deploy -c $file name
